name: Run tests and publish report
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
            maven-version: 3.6.3

      - name: Run Test
        run: ./mvnw verify
        continue-on-error: true

      - name: Setup Allure History
        uses: actions/checkout@v4.2.2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.11
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history

      - name: Publish Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history