name: pass env
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  check-pr:
    strategy:
      matrix:
        target: ["a","b","c"]
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.check-prs.outputs.PR_NUMBER }}
    steps:
      - name: Check PRs
        id: check-prs
        run: |
          echo "PR_NUMBER=${{ env.PR_NUMBER }},${{ matrix.target }}" >> $GITHUB_OUTPUT

  publish:
    needs: [check-pr]
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ needs.check-pr.outputs.pr-number }}
    steps:
      - name: print
        run: |
          echo "abc: ${PR_NUMBER}"