name: Reusable workflow example

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - run: echo "yoyo ${{ inputs.target }}"