name: Reusable workflow example

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string


jobs:
  before:
    runs-on: ubuntu-latest
    steps:
      - run: printf "some long message\nwith newlines\n" > $HOME/file.txt

  sample:
    runs-on: ubuntu-latest
    needs: before
    steps:
      - run: cat $HOME/file.txt