name: workflow.yml
on:
  workflow_dispatch:
  pull_request:

env:
  WORKFLOW_VARIABLE: "value"
jobs:
  check-pr:
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.check-prs.outputs.PR_NUMBER }}
    steps:
      - name: Check PRs
        id: check-prs
        run: |
          # ...
          echo "PR_NUMBER=$pr_number" >> $GITHUB_OUTPUT

  publish:
    needs: [check-pr]
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ needs.check-pr.outputs.pr-number }}
#  job1:
#    runs-on: ubuntu-latest
#    outputs:
#      output1: $
#      output2: $
#    steps:
#      - id: step1
#        run: echo "test=hello" >> "$GITHUB_OUTPUT"
#      - id: step2
#        run: echo "test=world" >> "$GITHUB_OUTPUT"
#  job2:
#    runs-on: ubuntu-latest
#    needs: job1
#    steps:
#      - env:
#          OUTPUT1: $
#          OUTPUT2: $
#        run: echo "$OUTPUT1 $OUTPUT2"

#  matrixJob:
#    runs-on: ubuntu-latest
#    outputs:
#      output1: $
##    strategy:
##      matrix:
##        target: ["a","b","c"]
#    steps:
#      - id: set-output
#        run: echo "test=test123" >> "$GITHUB_OUTPUT"
#       # run: echo "test=${{ matrix.target }}" >> "$GITHUB_OUTPUT"
#  consumer:
#    runs-on: ubuntu-latest
#    needs: matrixJob
#    steps:
#      - env:
#          OUTPUT1: $
#        run: echo "$OUTPUT1"

