name: yo.yml
on:
  workflow_dispatch:

env:
  myvar: 'hello'

jobs:
  yo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ls all
        shell: bash
        run: echo $myvar
